{% set name = "reacttrs" %}
{% set version = "0.2.1" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: 6a2cbf7a209deb0be056cc30e7c7c5f1ff5a744cba18c427d5418cc32bb1e53c

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 1

requirements:
  host:
    - python {{ python_min }}
    - pip
    - hatchling
  run:
    - python >={{ python_min }}

test:
  imports:
    - reacttrs
  requires:
    - pip
    - python {{ python_min }}
  commands:
    - pip check

about:
  home: https://github.com/davidbrochart/reacttrs
  summary: Attributes with superpowers
  license: MIT
  license_family: MIT
  license_file: LICENSE
  dev_url: https://github.com/davidbrochart/reacttrs

extra:
  recipe-maintainers:
    - martinRenou
    - davidbrochart
